backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: Image, name: image, widget: image}
          - {label: Name, name: name, widget: string}
          - {label: Occupation, name: occupation, widget: string}
          - {label: Email, name: email, widget: object, fields: [{label: Caption, name: caption, widget: string}, {label: Link, name: link, widget: text}]}
          - {label: Description, name: description, widget: markdown}
          - label: "References"
            name: "references"
            widget: "list"
            summary: '{{fields.quote}} - {{fields.author.name}}'
            fields:
              - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
              - label: Author
                name: author
                widget: object
                fields:
                  - {label: Name, name: name, widget: string, default: "Job Wind"}
                  - {label: Description, name: description, widget: string, default: "Owner at Monkey Station"}
          - {label: Education, name: education, widget: list}
          - {label: Development Skills, name: dev_skills, widget: string}
          - {label: Design Skills, name: design_skills, widget: string}
          - {label: LinkedIn, name: linkedin, widget: object, fields: [{label: Caption, name: caption, widget: string}, {label: Link, name: link, widget: text}]}

          
          